### ISSUE TITLE
Unable to load bupaR > no package called ‘later’

### ISSUE THREAD

**Issue by larspijnappel** [gertjanssenswillen/bupaR#13]
```
Error: package or namespace load failed for ‘bupaR’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘later’
```

This issue remains even after reinstalling: bupaR:

```
Installing package into ‘C:/Users/.../Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bupaR_0.4.1.zip'
Content type 'application/zip' length 136625 bytes (133 KB)
downloaded 133 KB
```

Manually installing package `later` did the trick BTW.

**Comment by gertjanssenswillen** [comment]
Thank for your patience.

It seems there was a package version of `later` on August, 31st which is probably related to this. Its not clear what the problem is though. Since it worked after installing that package I'll just leave this issue open to see if there are others with the same problem, which could indicate it is caused by bupaR or not.
